site_name: Zettelkasten
repo_url: https://github.com/wobintosh/fami-einfuehrung
nav:
    - Start: index.md
    - FaMI-Einführung: 
        - Archivkunde: 
            - Abgabe & Bewertung: einfuehrung/archiv/abgabe_bewertung.md
            - Archivgut (Arten): einfuehrung/archiv/archivgut.md
            - Archivportale: einfuehrung/archiv/archivportale.md
            - Archivrecht: einfuehrung/archiv/archivrecht.md
            - Archivsparten/-typen: einfuehrung/archiv/archivsparten.md
            - Archivtechnik: einfuehrung/archiv/archivtechnik.md
            - Begriffsdefinitionen: einfuehrung/archiv/definitionen.md
            - Benutzung: einfuehrung/archiv/benutzung.md
            - Bestandserhaltung: einfuehrung/archiv/bestandserhaltung.md
            - Erschließung/Verzeichnung: einfuehrung/archiv/erschliessung.md
            - Ordnungsprinzipien: einfuehrung/archiv/ordnungsprinzipien.md
        - Bibliothek: 
            - Bestandsarten: einfuehrung/bibliothek/bestandsarten.md
            - Bestandserhaltung: einfuehrung/bibliothek/bestandserhaltung.md
            - Bestandsrevision: einfuehrung/bibliothek/bestandsrevision.md
            - Bibliotheksarten: einfuehrung/bibliothek/bibliotheksarten.md
            - Buchbearbeitung: einfuehrung/bibliothek/buchbearbeitung.md
            - Buchhandel: einfuehrung/bibliothek/buchhandel.md
            - ekz: einfuehrung/bibliothek/ekz.md
            - Erwerbung: einfuehrung/bibliothek/erwerbung.md
            - Geschäftsgang: einfuehrung/bibliothek/geschaeftsgang.md
            - Kataloge: einfuehrung/bibliothek/kataloge.md
            - Magazinierung: einfuehrung/bibliothek/magazinierung.md
            - Makulierung: einfuehrung/bibliothek/makulierung.md
            - Medientypen: einfuehrung/bibliothek/medientypen.md
            - Publikationsformen: einfuehrung/bibliothek/publikationsformen.md
            - Recherche: einfuehrung/bibliothek/recherche.md
            - Sondersammlungen (SDD, SSG): einfuehrung/bibliothek/sondersammlungen.md
            - Verbünde: einfuehrung/bibliothek/verbuende.md
            - Wichtige Abkürzungen: einfuehrung/bibliothek/abkuerzungen.md
        - Bildagentur: einfuehrung/bildagentur.md
        - Information & Dokumentation: 
            - Begriffe: einfuehrung/information_dokumentation/begriffe.md
            - Dokumentation: einfuehrung/information_dokumentation/dokumentation.md
            - Fachinformationszentren: einfuehrung/information_dokumentation/fachinformationszentren.md
            - Hosts: einfuehrung/information_dokumentation/hosts.md
            - Informationsformen & -träger: einfuehrung/information_dokumentation/informationsformen.md
        - Medizinische Dokumentation: einfuehrung/medizinische_dokumentation.md
        - Politik:
            - Arbeitszeiten: einfuehrung/politik/arbeitszeiten.md
            - Arbeitszeugnis: einfuehrung/politik/arbeitszeugnis.md
            - Ausbildung: einfuehrung/politik/ausbildung.md
            - Kündigungsschutz: einfuehrung/politik/kuendigungsschutz.md
            - Urlaubsanspruch: einfuehrung/politik/urlaub.md
        - Wirtschaft:
            - Angebote vergleichen: einfuehrung/wirtschaft/angebot_vergleichen.md
            - Arbeitsteilung: einfuehrung/wirtschaft/arbeitsteilung.md
            - Bankgeschäfte: einfuehrung/wirtschaft/bankgeschaefte.md
            - Bedürfnisse: einfuehrung/wirtschaft/beduerfnisse.md
            - Grundprinzipien: einfuehrung/wirtschaft/grundprinzipien.md
            - Güter: einfuehrung/wirtschaft/gueter.md
            - Kaufvertrag: einfuehrung/wirtschaft/kaufvertrag.md
            - Öffentliche Daseinsfürsorge: einfuehrung/wirtschaft/oeffentliche_daseinsvorsorge.md
            - Öffentliche Unternehmen: einfuehrung/wirtschaft/oeffentliche_unternehmen.md
            - Organisationsformen: einfuehrung/wirtschaft/organisationsformen.md
            - Preisbildung: einfuehrung/wirtschaft/preisbildung.md
            - Rechtsfähigkeit: einfuehrung/wirtschaft/rechtsfaehigkeit.md
            - Rechtsgeschäfte: einfuehrung/wirtschaft/rechtsgeschaefte.md
            - Vertragsarten: einfuehrung/wirtschaft/vertragsarten.md
            - Zahlungsmöglichkeiten: einfuehrung/wirtschaft/zahlungsmoeglichkeiten.md
        - Lernzettel Abschlussprüfung: einfuehrung/lernzettel/index.md
        - Urheberrecht bei Bildern: 
            - Urheberrecht & Persönlichkeitsrechte: einfuehrung/urheberrecht/bildrechte.md
            - Verwertungsrechte: einfuehrung/urheberrecht/verwertungsrechte.md
        - Hilfsmittel: einfuehrung/hilfsmittel.md
    - Kulturelles Erbe in Serien: varia/kulturelles-erbe-serien.md
    - IT:
        - Bash-Helferlein: it/bash.md
        - Excel: it/excel.md
    - Nachschlagewerke: 
        - Allgemeine: nachschlagewerke/allgemein.md
        - Biografische: nachschlagewerke/biografisch.md
        - Design & Typografie: nachschlagewerke/design-typografie.md
        - Politik & Recht: nachschlagewerke/politik-recht.md
        - Regional & thematisch: nachschlagewerke/regional-thematisch.md
        - Wikidata: nachschlagewerke/wikidata.md
        - Wörterbuch: nachschlagewerke/wörterbücher.md
    - Datenschutz: https://blog.grdl.eu/datenschutz/
    - Impressum: https://blog.grdl.eu/impressum/
theme: 
    name: material
    language: de
    font: false
    features:
        - search.highlight
markdown_extensions:
    - toc: 
        permalink: true
    - footnotes
    - mdx_truly_sane_lists
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.keys
plugins:
    - search:
        lang: de
    - git-revision-date
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wobintosh
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/wobintosh
      name: Github
    - icon: fontawesome/regular/bookmark
      link: https://blog.grdl.eu
      name: Blog

extra_javascript:
    - _js/tablesort.min.js
    - _js/tables.js